Repository itsnameissteven/Refactor-Tractor-Fitlit, pull requests merged in 2021-02, with the labels that each got.

#21 Feature/hydration
  src/Hydration.js
  test/hydration-test.js
Labels: Need Review

#23 Feature/activity class
  .DS_Store
  .eslintrc
  src/.DS_Store
  src/Activity.js
  test/activity-test.js
  test/userrepo-test.js
Labels: Need Review

#25 Feature/setup api
  src/API.js
  src/index.html
  src/scripts.js
Labels: Need Review

#27 Fix/Feature/class-refactor
  .gitignore
  src/Activity.js
  src/Calculation.js
  src/Hydration.js
  src/Sleep.js
  src/User-repo.js
  test/Calculation-test.js
  test/activity-test.js
  test/hydration-test.js
  test/sleep-test.js
  test/user-test.js
  test/userrepo-test.js
Labels: Class, Need Review, enhancement

#28 Feature/html and sass
  src/css/_base.scss
  src/css/_grid.scss
  src/css/_mixins.scss
  src/css/_style.scss
  src/css/_typography.scss
  src/css/_variables.scss
  src/css/base.scss
  src/css/index.scss
  src/css/style.scss
  src/images/sleep.svg
  src/images/walk.svg
  src/images/water.svg
  src/index.html
  src/scripts.js
Labels: Need Review

#29 Feature/dom api
  .eslintrc
  src/API.js
  src/User-repo.js
  src/scripts.js
Labels: Need Review

#30 Fix/dom api refactor
  src/Activity.js
  src/scripts.js
Labels: Need Review, bug

#33 Feature/chart.js
  package-lock.json
  package.json
  src/Calculation.js
  src/Hydration.js
  src/css/_grid.scss
  src/css/_mixins.scss
  src/css/_style.scss
  src/css/_typography.scss
  src/dataChart.js
  src/index.html
  src/scripts.js
Labels: Need Review

#36 Fix/get request on pageload
  src/scripts.js
Labels: Need Review, User Stories

#37 Feature/data organization
  src/Hydration.js
  src/css/_style.scss
  src/dataChart.js
  src/index.html
  src/scripts.js
  test/Calculation-test.js
  test/activity-test.js
  test/hydration-test.js
  test/sleep-test.js
Labels: Need Review

#38 Feature/entry popup
  .eslintrc
  src/API.js
  src/css/_style.scss
  src/index.html
  src/scripts.js
Labels: CSS/HTML, enhancement

#41 Fix html issue
  src/index.html
Labels: bug

#43 Feature/fine tune popup
  src/css/_style.scss
  src/css/_variables.scss
  src/images/check.svg
  src/images/warning.svg
  src/index.html
  src/scripts.js
Labels: CSS/HTML
