Repository itsnameissteven/Refactor-Tractor-Fitlit, pull requests merged in 2021-03, with the labels that each got.

#44 Feature/restyle
  src/css/_style.scss
  src/css/_typography.scss
  src/images/hamburger.svg
  src/index.html
  src/scripts.js
Labels: Need Review

#45 Feature/post requests
  src/API.js
  src/Activity.js
  src/Calculation.js
  src/css/_style.scss
  src/scripts.js
Labels: Need Review, enhancement

#46 Feature/sad path
  src/User-repo.js
  src/css/_style.scss
  src/dataChart.js
  src/images/calendar.svg
  src/images/daily.svg
  src/images/user.svg
  src/index.html
  src/scripts.js
Labels: Need Review

#47 Fix/refactor tests
  src/Activity.js
  src/Hydration.js
  src/Sleep.js
  src/User-repo.js
  src/images/tractor.svg
  test/activity-test.js
  test/hydration-test.js
  test/sleep-test.js
Labels: Class, Need Review

#48 Feature/scripts.js refactor
  .eslintrc
  src/css/_mixins.scss
  src/css/_style.scss
  src/css/_typography.scss
  src/css/_variables.scss
  src/dataChart.js
  src/scripts.js
Labels: Need Review

#49 Fix image links
  src/index.html
Labels: Need Review
